language: python
python:
  - "2.7"
  #- "nightly" # currently points to 3.7-dev
#before_install:
#    - sudo apt-get update -qq
#    - sudo apt-get build-dep -qq python-pygame
#    - sudo apt-get install -qq python-pygame
# command to install dependencies
install: "pip install -r travis_requirements.txt"
# command to run tests
script: py.test

after_sucess:
  #https://codeclimate.com
  - CODECLIMATE_REPO_TOKEN=756ba76da2c8a803f7b5580cbaffcaa30f3934184ea9afd2fb59f526dfee30a9 codeclimate-test-reporter